image: node:latest

stages:
  - install
  - build
  - test

cache:
  key: one-key-to-rule-them-all
  paths:
    - node_modules/
    - ventoli-model/node_modules/
    - ventoli-front/node_modules/
    - ventoli-api/node_modules/
    - ventoli-server/node_modules/
    - .yarn

run_install:
  stage: install
  script:
    - yarn install --cache-folder .yarn

run_build:
  stage: build
  script:
    - yarn lerna run --scope @ventoli/ventoli-model build
  artifacts:
    paths:
      - ventoli-model/dist/

run_tests:
  stage: test
  script:
    - yarn lerna run test
