image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - ventoli-model/node_modules/
    - ventoli-front/node_modules/
    - ventoli-api/node_modules/

install_dependencies:
  stage: build
  script:
    - cd ventoli-model
    - yarn link
    - yarn install
    - cd ..
    - cd ventoli-front
    - yarn link "@ventoli/ventoli-model"
    - yarn install
    - cd ..
    - cd ventoli-api
    - yarn link "@ventoli/ventoli-model"
    - yarn install
  artifacts:
    paths:
      - ventoli-model/node_modules/
      - ventoli-front/node_modules/
      - ventoli-api/node_modules/

run_tests:
  stage: test
  script:
    - cd ventoli-model
    - yarn run test
    - cd ..
    - cd ventoli-front
    - yarn run test
    - cd ..
    - cd ventoli-api
    - yarn run test
