image: node:latest

stages:
  - build
  - test

cache:
  key: one-key-to-rule-them-all
  paths:
    - node_modules/
    - ventoli-model/node_modules/
    - ventoli-front/node_modules/
    - ventoli-api/node_modules/
    - .yarn

install_dependencies:
  stage: build
  script:
    - yarn install --cache-folder .yarn
    - yarn lerna run build
  artifacts:
    paths:
      - ventoli-model/dist/

run_tests:
  stage: test
  script:
    - yarn lerna run build
